project:
  type: website
  output-dir: docs

website:
  title: "Poseidon Blog"
  navbar:
    logo: Poseidon-Avatar-White-BgSml.jpg
    right:
      - about.qmd
      - icon: github
        href: https://github.com/poseidon-framework
      - icon: mastodon
        href: https://ecoevo.social/@poseidon